### ISSUE TITLE
License for image files

### ISSUE THREAD

**Issue by rogers0** [xtaci/smux#11]
Hi there,

Thanks for working on this project.
I'm going to package this to Debian. However, according to rule of Debian, every file should be cleared in license.
So I'm writing to you to double confirm the following file:
 curve.jpg  mux.jpg  smux.png

Are you created the above 3 files by yourself? If so, we can safely treat it same as the code you wrote, so it's MIT/Expat license.
But if you borrow some files from other project, please let me know. So I can trace the license of each image file.
Thank you!

Cheers,
Roger

**Comment by xtaci** [comment]
mux.jpg comes from http://www.transtutors.com/homework-help/computer-science/networking/telephony/multiplexing/

curve.jpg comes from screenshot of youtube https://www.youtube.com/watch?v=C9h88KTBlY0

smux.png is created by myself.

**Comment by rogers0** [comment]
@xtaci just FYI. Currently Debian is under Stretch release freeze stage, so our package is still in waiting queue to be uploaded to the archive. Nothing to worry about so far.
