### ISSUE TITLE
smux做了哪几件事情？

### ISSUE THREAD

**Issue by rafw** [xtaci/smux#13]
我看了您的文档，想跟你确认一下几个问题。
1，smux是不是做了如下几件事：
a) 多路复用，编程接口上在a和b间建立多次连接，实际上a和b之间只有一条链接
b) 可靠性，kcp-go未模拟TCP的三次握手、连接断开、连接超时，smux实现了这些，使其使用上更向TCP
c) 顺序性，kcp-go收到的数据可能乱序，用smux可以保证顺序，对这一点我很费解，是我理解错了吧

2，用上smux，每个udp包将多花费8个字节

谢谢！

**Comment by xtaci** [comment]
smux只做了多路复用，就是多个tcp流汇入一条tcp 流，就这一件事
可靠性和顺序性是tcp保证的。

**Comment by xtaci** [comment]
至于流的开关控制命令，自然也是需要的。

**Comment by metalwood** [comment]
现在我直接使用kcp－go的接口进行编程，发现连接的建立和关闭在接口上都没有体现（比如客户端Dial服务端，目前看总是成功的，还是说这是我的代码问题），这样使用起来不方便。现在的问题是，如何实现连接建立、关闭、断开（异常关闭）？谢谢。

**Comment by xtaci** [comment]
一般是通过应用层的超时实现的，心跳包，比如5s

**Comment by xtaci** [comment]
`net.Conn  SetReadDeadline`
