### ISSUE TITLE
丢包问题

### ISSUE THREAD

**Issue by huyuguang** [xtaci/smux#20]
因为多路复用底层一条通路，那么是否意味着也存在http2.0的head-of-line blocking问题？线路上丢了一个包，滑动窗口减小，是否意味着在此线路上复用的所有连接全都被降速了？

**Comment by jannson** [comment]
应该是这样的问题，毕竟它是一个 simple mux。

**Comment by f4nff** [comment]
这个问题我也遇到了,如果网络不稳定,会限速,正常50Mbps,出现这种情况之后不到1Mbps,
断开重新连接之后恢复正常.
