### ISSUE TITLE
Stream ID reuse

### ISSUE THREAD

**Issue by AudriusButkevicius** [xtaci/smux#21]
So not sure if this is an issue, so treat it as a question.

1. Imagine B connects to A, establish a single stream.
2. Imagina B crashes and restarts within a short period of time.
3. B reattempts to connect to A
4. B thinks it's establishing a new stream where as the stream is mid-way on A (given there is no RST)

**Comment by xtaci** [comment]
no problem, B should choose a different port.

**Comment by AudriusButkevicius** [comment]
Yeah but if you are trying to punch through NAT using stun, that does not happen, as one of the requirements to punch through is to dial and listen on the same port. 

It's even worse with KCP as KCP listener connections as keyed by address, not address+conversation id, so traffic from a new different conversation gets blackholed into some old dead connection.

**Comment by f4nff** [comment]
这确实是一个bug,
A是服务端,
B是客户端
b连接A
然后a关闭掉,
然后打开a
然后使用b连接,
第一次连接会失败,
第二次才会成功,

**Comment by f4nff** [comment]
只要客户端跟服务端断开,
也许是心跳包超时,
也许是服务端跟客户端中间网络断开,
或者服务端程序关闭之后重新打开,

> 然后第一次使用客户端进行连接的时候,都会提示**broken pipe**
> 第二次才会正常.
