### ISSUE TITLE
C implementation

### ISSUE THREAD

**Issue by dobegor** [xtaci/smux#22]
As kcp-go is compatible with the original C implementation of KCP, it makes sense to create a C version of smux as well.

Do you have any plans on this?

It would be especially useful for C/C++ multiplayer games with Go server.

**Comment by dobegor** [comment]
Or at least document a spec like yamux did.

**Comment by xtaci** [comment]
i have no plan on c version of smux. 

but it's only 600 lines of code, the frame definition is in the readme.md
