### ISSUE TITLE
Satisfy net.Conn

### ISSUE THREAD

**Issue by AudriusButkevicius** [xtaci/smux#3]
Given this is network oriented, it would make sense for it to satisfy net.Conn and for example deadlines.

**Comment by xtaci** [comment]
how to implement   `SetWriteDeadline(t time.Time) error`  for different streams on the same connection?

**Comment by AudriusButkevicius** [comment]
Well yamux does it somehow.

**Comment by xtaci** [comment]
but with problem

**Comment by AudriusButkevicius** [comment]
What problem?
I mean it's not feasible to have any networking library if you might end up hanging indefinately or for unreasonable amounts of time (say 30 seconds on a handshake)

**Comment by AudriusButkevicius** [comment]
As for implementation it's trivial, all the deadlines do is promise that next calls will not block for longer than X, no other sematics are implied by that.

**Comment by xtaci** [comment]
you have to set the underlying connection's WriteDeadLine to the closest one of all streams, or else, it will block when sockbuf is full.

so a possible solution is by maintaining a min-heap for time. when the closest deadline has reached, switch to the next one.

**Comment by AudriusButkevicius** [comment]
I think it's perfectly fine to discard data at some later point (after the write has returned), the idea is just not to block on the write for too long, if the send queue is full or something like that.

**Comment by xtaci** [comment]
you can't guarantee that if you do not set write deadline to for example TCPConn.

**Comment by AudriusButkevicius** [comment]
Well I suspect it's fine for the dispatching routine to block indefinately or to maintain a continious 1s deadline itself internally, yet it doesn't need to be related to the deadline of the stream.

**Comment by AudriusButkevicius** [comment]
I guess you need a deadline for Accept() on tye session for example.

**Comment by xtaci** [comment]
continuous 1s interrupt doesn't guarantee the atomicity of conn.Write for various underlying connections , you have to handle 'wrote incomplete data' problem, especially for TCPConn.

**Comment by AudriusButkevicius** [comment]
Fine, you can probably get away without a deadline there as the write call would return upon a close of tye connection anyway, not causing any routine leaks.
