### ISSUE TITLE
stream.Close() stuck if buffer is full

### ISSUE THREAD

**Issue by MingchenZhang** [xtaci/smux#37]
If the underlying buffer of net.Conn is full (any may be full forever), it would block the write call to smux stream. If a Close() is called on the stream, it would attempt to write cmdFIN, but this write blocks as well. 
The keepalive() goroutine should come and save the day, but it is also stuck at sending cmdNOP. This leaves no one watching on tickerTimeout, and the Close() function of the underlying net.Conn wouldn't be called to resolve the deadlock. 
My program sometime gets into a stuck and i believe this is the reason. Could someone take a look? Or I made a mistake in understanding the code?

**Comment by sintanial** [comment]
Any update ? 
I think, to solve this problem, need to add deadline when write data to connect in this line 
https://github.com/xtaci/smux/blob/b993df6776bd954c5d7dc069590b5b1a688fa2be/session.go#L317

**Comment by jannson** [comment]
The keepalive is timeout when all writing operations blocked, and then the session closed!

**Comment by xtaci** [comment]
solved?
