### ISSUE TITLE
How to tell if an smux is closed?

### ISSUE THREAD

**Issue by WinstonPrivacy** [xtaci/smux#44]
Question: We have an smux opened between two peers across the internet. If the remote peer goes down, how can we detect this?

We looked at session.IsClosed() but it doesn't seem to fire when the remote peer shuts downso session.OpenStream() is returning a stream. When we attempt to use this, it predictably fails.

**Comment by xtaci** [comment]
In most cases OpenStream will return false if the session has closed, but there is indeed a race condition when Close() and OpenStream() is happening at the same time.

**Comment by xtaci** [comment]
https://github.com/xtaci/smux/releases/tag/v1.2.6
