### ISSUE TITLE
Which version is the last?

### ISSUE THREAD

**Issue by Green7** [xtaci/smux#63]
I ask because:
- if I do get github.com/xtaci/smux/ (without initialized modules) go will download the version 1.5.10
- if I do get github.com/xtaci/smux/ with initialized modules go will download version 2.0.1+incompatible 

I'm using modules I realized that I am still using version 2.0.1. So I want to update the version. Which one should I use? (1.5.10 or 2.1.0?)

**Comment by xtaci** [comment]
1.5.10 , all features in 2.x.x branch have been merged into 1.x.x

**Comment by Green7** [comment]
Thank you for the information. It is safe to change version from 2.0.1 to 1.5.10 or should I expect problems and major changes in the code?

**Comment by xtaci** [comment]
it's safe!

**Comment by Green7** [comment]
Great :)

**Comment by xtaci** [comment]
just remember to set the Version in smux.Config，if you are using version:2
