### ISSUE TITLE
stream.SetDealine not work if stream is already hang up after executing stream.waitRead

### ISSUE THREAD

**Issue by LukeLandWalker** [xtaci/smux#64]
stream.SetReadDeadline not work if stream is already hang up after executing stream.waitRead.

**Comment by xtaci** [comment]
https://github.com/xtaci/smux/commit/d2d7690bcce62fc6978666a2559c0d8bd3bf0036
try this commit

**Comment by LukeLandWalker** [comment]
> [d2d7690](https://github.com/xtaci/smux/commit/d2d7690bcce62fc6978666a2559c0d8bd3bf0036)
> try this commit

OK, I'll try.

**Comment by LukeLandWalker** [comment]
> [d2d7690](https://github.com/xtaci/smux/commit/d2d7690bcce62fc6978666a2559c0d8bd3bf0036)
> try this commit

It works! THX!
