### ISSUE TITLE
Multiplexing over SCTP unordered mode

### ISSUE THREAD

**Issue by rucciva** [xtaci/smux#95]
Hi, first of all, thanks for creating this library.

So i'm planning to forward UDP packet from multiple connections via SCTP (unordered) connection to remote UDP servers, something like SSH Tunnel but for UDP. Will this library runs fine when the underlying transport protocol does not guarantee order of packet?

**Comment by xtaci** [comment]
No, it's not multiplexing's responsibility to guarantee the order of packets, you may need https://github.com/xtaci/kcp-go

**Comment by rucciva** [comment]
noted, thanks @xtaci
